# set the location of the file using AWS_SHARED_CREDENTIALS_FILE
# usage:
# session = boto3.Session(profile_name='default')
#
# client = session.client('s3')
#
[default]
aws_access_key_id=DO003ZZWAE34HMFMRCQ3
aws_secret_access_key=Y+4Ld8Cu/PCOgtMUmWTFR1O00T4g5YpR15tAX177PJI
