name:                obsetl
version:             0.1.2.0
github:              "lucivia/obsetl"
license:             BSD3
author:              "Edmund Cape"
maintainer:          "edmund.cape@lucivia.com"
copyright:           "Lucivia LLC 2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lucivia/obsetl#readme>

ghc-options: -Wall -fno-warn-redundant-constraints

default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeOperators

dependencies:
  - aeson >= 1.4.6.0 && < 1.5
  - base >= 4.7 && < 5
  - bytestring >= 0.10.10.0 && < 0.20
  - containers >= 0.6.2.1 && < 0.7
  - vector >= 0.12.1.2 && < 0.13
  - monad-logger >= 0.3.32 && < 0.4
  - morpheus-graphql >= 0.10.0 && < 0.20
  - mtl >= 2.2.2 && < 3
  - optparse-applicative >= 0.15.1.0 && < 0.20
  - protolude
  #- raw-strings-qq >= 1.1 && < 1.2
  - safe-exceptions >= 0.1.7.0 && < 0.2
  - servant-server >= 0.16.2 && < 0.26
  - text >= 1.2.4.0 && < 1.3
  - transformers >= 0.5.6 && < 0.6
  - wai >= 3.2.2.1 && < 3.3
  - wai-cors >= 0.2.7 && < 0.3
  - wai-extra >= 3.0.29.1 && < 3.1
  - warp >= 3.3.9 && < 3.4
  - stm >= 2.5.0.0 && < 2.6

library:
  source-dirs: src

executables:
  obsetl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - obsetl

tests:
  obsetl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - obsetl
