name:                obsetl
version:             0.1.4.1
github:              "lucivia/obsetl"
author:              "Edmund Cape"
maintainer:          "edmund.cape@lucivia.com"
copyright:           "Lucivia LLC 2022"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/lucivia/obsetl#readme>

ghc-options: -Wall -fno-warn-redundant-constraints

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeOperators

dependencies:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - base64 >= 0.4.2.3
  - bytestring >= 0.10.10.0 && < 0.20
  - containers >= 0.6.2.1 && < 0.7
  - hslogger >= 1.3.1.0 && < 1.4
  - monad-logger >= 0.3.32 && < 0.4
  - morpheus-graphql >= 0.17.0
  - morpheus-graphql-core >= 0.17.0
  - mtl >= 2.2.2 && < 3
  - optparse-applicative >= 0.15.1.0 && < 0.20
  - protolude
  - safe-exceptions >= 0.1.7.0 && < 0.2
  - servant-server >= 0.16.2 && < 0.26
  - stm >= 2.5.0.0 && < 2.6
  - text >= 1.2.4.0 && < 1.3
  - template-haskell >= 2.14.0.0 && < 2.20
  - transformers >= 0.5.6 && < 0.6
  - vector >= 0.12.1.2 && < 0.13
  - wai >= 3.2.2.1 && < 3.3
  - wai-cors >= 0.2.7 && < 0.3
  - wai-extra
  - warp >= 3.3.9 && < 3.4
  - text-conversions

library:
  source-dirs: src

executables:
  obsetl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - obsetl

tests:
  obsetl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - obsetl
    - tasty >= 0.7
    - tasty-hunit >= 0.10.0.2
    - tasty-hspec >= 1.1.5.1
    - tasty-quickcheck >= 0.10.1.1
    - tasty-rerun >= 1.1.17
#    - generic-random >= 1.3.0.0 && < 1.4
