mutation createObsETL($obsVar: ObsEtlInput!) {
  newObsEtl(value: $obsVar) {
    subject {
      qualities {
        qualityName
      }
      subjectType
    }
    measurements {
      measurementType
      components {
        componentName
        componentValues {
          __typename
          ... on TxtValues {
            txtValues
          }
          ... on IntValues {
            intValues
          }
          ... on SpanValues {
            spanValues {
              rangeStart
              rangeLength
              reduced
            }
          }
        }
      }
    }
  }
}
