query matrix($input: RequestInput!) {
  reqMatrixSpec(requestSpec: $input) {
    subExpression {
      source {
        codomain
      }
    }
    meaExpressions {
      filter {
        fieldName {
          value
        }
      }
    }
  }
}
